name: Blog Deploy

on: 
  push:
    branches: 
      - dev

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1
        
      - name: 2. setup nodejs...
        uses: actions/setup-node@v1
      
      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm install
          
      - name: 4. hexo generate public files...
        run: |
          npm run clean
          npm run build
          copy CNAME public

      - name: 5. deploy 'public files'
        run: |
          git config --global user.name "w-xuefeng"
          git config --global user.email "xuefeng@kcalb.wang"    
          cd public
          dir
          git init
          git remote add origin https://w-xuefeng:${{secrets.key}}@github.com/w-xuefeng/blog.git
          git add .
          git commit -am "Deployed by GitHub Actions ..."
          git push -u origin master -f
